//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HC_ESTADOS_USUARIOS> HC_ESTADOS_USUARIOS { get; set; }
        public virtual DbSet<HC_USUARIOS> HC_USUARIOS { get; set; }
        public virtual DbSet<HC_ANIMAL> HC_ANIMAL { get; set; }
        public virtual DbSet<HC_CLASE_ANIMAL> HC_CLASE_ANIMAL { get; set; }
    }
}
